
from enum import Flag


class DownloadMode(Flag):
    NULL = 0
    SAVE_PICTURES = 1
    SAVE_TO_FOLDER = 10
    SAVE_PSD = 100
    SAVE_TO_ARCHIVE = 1000
    MARK_NUMERATION = 10000

    STANDARD = SAVE_PICTURES | SAVE_TO_FOLDER | MARK_NUMERATION
    SAVE_PSD_PICTURE_TO_ARCHIVE = SAVE_PSD | SAVE_PICTURES | SAVE_TO_ARCHIVE | MARK_NUMERATION