from parsers.BatoToParser import BatoToParser
from parsers.XBatoParser import XBatoParser
from parsers.MangaParserInterface import MangaParserInterface
from parsers.KaoruHanaWarinToSakuParser import KaoruHanaWarinToSakuParser