from userInterface.DownloadChaptersFrame import DownloadChaptersFrame
from userInterface.MainWindow import MainWindow
from userInterface.ChaptersList import ChaptersList
from userInterface import Setup